### ISSUE TITLE
Second deployment problem

### ISSUE THREAD

**Issue by suntong** [nghiepdev/freetext.nghiep.dev#1]
Hi, 

Thanks for providing such a wonderful project. 

Just that I found that, for me, it just cannot survive a second deployment, even after just seconds later and pass everything!!!
The deployed is not runnable:

![image](https://user-images.githubusercontent.com/422244/200373892-2071132c-4949-402d-b5d5-70a9601974b7.png)

Be careful when trying to replicate it at your side!

**Comment by nghiepdev** [comment]
Looks like you haven't provided `APP_DETA_PROJECT_KEY ` env.
![image](https://user-images.githubusercontent.com/4768095/200377739-2fe2261e-0ba2-4235-a18a-6eafd720e713.png)

**Comment by suntong** [comment]
Ahh, BINGO!!!

Thanks for such swift answer!
